# Generated by Django 4.1.7 on 2023-03-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='nome_pesquisa',
            field=models.CharField(default='', max_length=100),
        ),
    ]
