# Generated by Django 4.1.7 on 2023-03-30 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_fotografia_nome_pesquisa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='nome_pesquisa',
        ),
    ]
